# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Configure NuGet
      run: |
        sed -i 's/%USERNAME%/${{ github.actor }}/' BlazorLibrary/nuget.config
        sed -i 's/%PASSWORD%/${{ secrets.NUGET_API_KEY }}/' BlazorLibrary/nuget.config
    - name: Restore dependencies
      run: dotnet restore --configfile BlazorLibrary/nuget.config
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
